title: Github Pages
theme: minima
author: Ignacio Iacovino
email: nacho.iacovino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a description

# social links
twitter_username: twitter
github_username:  naknekv

show_excerpts: true # set to false to remove excerpts on the homepage
